package:
  name: ta-lib
  version: 0.4.17
  build: 9

source:
  - url: https://github.com/mrjbq7/ta-lib/archive/TA_Lib-0.4.17.tar.gz
    md5: 712242940ea994e632b409259c057d95
    folder: wrapper
  - url: http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    md5: 308e53b9644213fc29262f36b9d3d9b9
    folder: library

requirements:
  build:
    - python=3.7.*
    - cython=0.29.7
    - numpy=1.16.4
  run:
    - python=3.7.*
    - numpy=1.16.*

test:
  imports:
    - talib

about:
  home: http://github.com/mrjbq7/ta-lib
  license: BSD License
