package:
  name: ta-lib
  version: !!str 0.4.17
  build: 5

source:
  - url: https://github.com/mrjbq7/ta-lib/archive/TA_Lib-0.4.17.tar.gz
    md5: 712242940ea994e632b409259c057d95
    folder: wrapper
  - url: http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
    md5: 308e53b9644213fc29262f36b9d3d9b9
    folder: library

requirements:
  build:
    - python
    - cython
    - numpy x.x
  run:
    - python
    - numpy x.x

test:
  imports:
    - talib

about:
  home: http://github.com/mrjbq7/ta-lib
  license: BSD License
